FROM cypress/base:10

ENV APP_HOME /usr/src/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME

RUN node --version
RUN npm --version

EXPOSE 9001

RUN npm install -g wait-on --silent
RUN npm install --silent
RUN npm i -g npm@latest

CMD ["npm", "start"]