FROM node:10

ENV APP_HOME /usr/src/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME

RUN node --version
RUN npm --version

ENV CI=1

RUN npm install -g wait-on --silent
RUN npm install --silent
RUN npm i -g npm@latest

CMD ["npm", "start"]

HEALTHCHECK --interval=3m --timeout=1m \
  CMD curl --fail -s http://localhost:9001/ || exit 1