FROM cypress/included:4.4.0

ENV APP_HOME /usr/src/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# install packages
RUN apt-get update && \
    apt-get install -y curl \
    wget \
    default-jre \
    libgtk2.0-0 \
    libgtk-3-0 \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb
ENV JAVA_HOME=/usr/lib/jvm/default-java

EXPOSE 9001

# Override default entrypoint from cypress/included
ENTRYPOINT []

# avoid many lines of progress bars during install
# https://github.com/cypress-io/cypress/issues/1243
ENV CI=1

# disable shared memory X11 affecting Cypress v4 and Chrome
# https://github.com/cypress-io/cypress-docker-images/issues/270
ENV QT_X11_NO_MITSHM=1
ENV _X11_NO_MITSHM=1
ENV _MITSHM=0

# point Cypress at the /root/cache no matter what user account is used
# see https://on.cypress.io/caching
ENV CYPRESS_CACHE_FOLDER=/root/.cache/Cypress
RUN npm install -g wait-on --silent

COPY package.json $APP_HOME
COPY package-lock.json $APP_HOME

RUN npm ci --silent
RUN $(npm bin)/cypress verify

# Cypress cache and installed version
# should be in the root user's home folder
RUN cypress cache path
RUN cypress cache list
RUN cypress info

COPY . $APP_HOME