name: Cypress tests on MacOS - all browsers

on:
  schedule:
    # every day at 01-00
    # - cron:  '0 1 * * *'
    - cron:  '45 10 * * *'

jobs:
  parallel-runs-across-browsers:
    name: MacOS-${{ matrix.browser }}
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 7 copies of the current job in parallel
        # and they will load balance all specs
        browser: ['chrome', 'firefox', 'edge']
        machines: [ 1, 2, 3, 4, 5, 6 ]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:9001'
          wait-on-timeout: 300
          record: true
          parallel: true
          group: MacOS-${{ matrix.browser }}
          browser: ${{ matrix.browser }}
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}