name: Cypress tests

on: [pull_request]

jobs:
  fork-test:
    if: (${{ github.head_ref}} != 'chrisbarber86/carbon')
    name: Cypress regression for forked PR
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress regression for forked PR
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: "http://localhost:9001"
          wait-on-timeout: 250
          record: true
          parallel: true
          group: Ubuntu-chrome
          browser: chrome
          headless: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
